id: IB92BAE0C
legacy_id: P003243
ocr_import_info:
  bdrc_scan_id: W1CZ1878
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T20:47:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:07:39.989659+00:00'
last_modified: 2022-08-31 03:07:56.772807
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1878
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1878
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོ་རྗེ་ཕག་མོའི་ཟབ་ཁྲིད་ཀྱི་ཆོས་སྐོར།
  author: བསྟན་གཉིས་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.3942162894473923
  ocr_word_median_confidence_index: 0.30000001192092896
quality: null
bases:
  I1CZ1961:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1961
      total_pages: 184
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1961.txt
    statistics:
      ocr_word_median_confidence_index: 0.30000001192092896
      ocr_word_mean_confidence_index: 0.3942162894473923
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
