id: IB92BAE0C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T20:48:33+00:00'
last_modified: '2022-06-07T18:36:37.743863+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1878
  title: རྡོ་རྗེ་ཕག་མོའི་ཟབ་ཁྲིད་ཀྱི་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7769':
      image_group_id: I1CZ1961
      title: ''
      total_pages: 184
      order: 1
      base_file: 7769.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
