id: P003243
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1878
  title: རྡོ་རྗེ་ཕག་མོའི་ཟབ་ཁྲིད་ཀྱི་ཆོས་སྐོར
  author: ''
  volumes:
    5164840cf2fb49b68571beb8d1597c2a:
      image_group_id: I1CZ1961
      title: ''
      volume_number: 1
      total_pages: 184
